#!/usr/bin/env node
/*
 * Generate dist/sw.js after `vite build`.
 *
 * Phase 7 was meant to bring this in via vite-plugin-pwa, but that plugin never
 * survived install here (workbox-build → es-abstract). The app is small and
 * fully static, so a hand-rolled service worker is less machinery than the
 * plugin and does the same job: precache every built file, serve it back when
 * the network is gone.
 *
 * Precache entries are stored as paths relative to the service worker, so the
 * same output works whether the app is served from `/` or a subdirectory.
 */
import { createHash } from 'node:crypto'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const dist = path.join(root, 'dist')

// Everything else in dist/ is part of the shell and gets precached.
const SKIP = new Set(['sw.js'])

async function collect(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...(await collect(full)))
      continue
    }
    const rel = path.relative(dist, full).split(path.sep).join('/')
    if (SKIP.has(rel) || rel.endsWith('.map')) continue
    files.push(rel)
  }
  return files.sort()
}

const files = await collect(dist)

// Cache name changes whenever any built byte changes, which is what triggers
// the new worker to drop the old cache on activate.
const fingerprint = createHash('sha256')
for (const rel of files) {
  fingerprint.update(rel)
  fingerprint.update(await readFile(path.join(dist, rel)))
}
const version = fingerprint.digest('hex').slice(0, 12)

const sw = `/* Generated by scripts/gen-sw.mjs — do not edit. */
const CACHE = 'obzor-${version}'
const PRECACHE = ${JSON.stringify(files, null, 2)}
const SHELL = 'index.html'

// Navigations wait this long for the network before the cached shell wins, so
// a flaky connection behaves like an offline one instead of hanging.
const NETWORK_TIMEOUT_MS = 3000

function url(relative) {
  return new URL(relative, self.registration.scope).toString()
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE)
      await cache.addAll(PRECACHE.map(url))
      await self.skipWaiting()
    })(),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys()
      await Promise.all(
        names.filter((name) => name.startsWith('obzor-') && name !== CACHE).map((name) => caches.delete(name)),
      )
      await self.clients.claim()
    })(),
  )
})

async function fromNetworkFirst(request) {
  const cache = await caches.open(CACHE)
  try {
    const response = await Promise.race([
      fetch(request),
      new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), NETWORK_TIMEOUT_MS)),
    ])
    if (response && response.ok) cache.put(request, response.clone())
    return response
  } catch {
    return (await cache.match(request)) ?? (await cache.match(url(SHELL)))
  }
}

async function fromCacheFirst(request) {
  const cache = await caches.open(CACHE)
  const hit = await cache.match(request)
  if (hit) return hit
  const response = await fetch(request)
  if (response && response.ok && request.url.startsWith(self.registration.scope)) {
    cache.put(request, response.clone())
  }
  return response
}

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return
  if (!request.url.startsWith(self.registration.scope)) return

  if (request.mode === 'navigate') {
    // A cached shell is the whole point: it is what makes the installed app
    // open with no network at all.
    event.respondWith(fromNetworkFirst(request).then((response) => response ?? fetch(request)))
    return
  }

  event.respondWith(fromCacheFirst(request))
})
`

await writeFile(path.join(dist, 'sw.js'), sw, 'utf8')

console.log(`\nWrote dist/sw.js — precaching ${files.length} files (obzor-${version})`)
