import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import type { Plugin, ResolvedConfig } from 'vite'

function normalizeBase(base: string): string {
  if (!base || base === '/') return '/'
  return base.endsWith('/') ? base : `${base}/`
}

function listFiles(dir: string, basePath: string, root = dir): string[] {
  const out: string[] = []
  for (const name of readdirSync(dir)) {
    if (name === 'sw.js') continue
    const full = join(dir, name)
    if (statSync(full).isDirectory()) {
      out.push(...listFiles(full, basePath, root))
    } else {
      const rel = relative(root, full).replaceAll('\\', '/')
      out.push(`${basePath}${rel}`)
    }
  }
  return out
}

function buildServiceWorker(urls: string[], cacheVersion: string, basePath: string): string {
  const navigateFallback = basePath
  const precache = JSON.stringify([navigateFallback, ...urls], null, 2)
  return `/* Auto-generated by vite-plugin-offline-sw - do not edit */
const CACHE = 'obzor-${cacheVersion}';
const PRECACHE = ${precache};
const NAVIGATE_FALLBACK = ${JSON.stringify(navigateFallback)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))),
    ).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(NAVIGATE_FALLBACK, copy));
          return response;
        })
        .catch(() => caches.match(NAVIGATE_FALLBACK)),
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (!response.ok) return response;
        const copy = response.clone();
        caches.open(CACHE).then((cache) => cache.put(request, copy));
        return response;
      });
    }),
  );
});
`
}

/** Precaches the production build into dist/sw.js without vite-plugin-pwa/workbox. */
export function offlineSwPlugin(): Plugin {
  let basePath = '/'

  return {
    name: 'offline-sw',
    apply: 'build',
    configResolved(config: ResolvedConfig) {
      basePath = normalizeBase(config.base)
    },
    closeBundle() {
      const dist = join(process.cwd(), 'dist')
      const urls = listFiles(dist, basePath)
      const cacheVersion = new Date().toISOString().replace(/[-:.TZ]/g, '').slice(0, 14)
      writeFileSync(join(dist, 'sw.js'), buildServiceWorker(urls, cacheVersion, basePath), 'utf8')
    },
  }
}
